<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="AssettoServer.RaceControl.Tests" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\Fps\*.kn5" />
    <EmbeddedResource Include="Assets\Fps\*.png" />
  </ItemGroup>
</Project>
