using System.Reflection;
using AssettoServer.Server.Fps;

namespace AssettoServer.Tests;

public sealed class FpsClientScriptTests
{
    [Test]
    public void CarrierCars_PreserveNativeParticipantStateAndDisableNativeLeaderboard()
    {
        Assembly assembly = typeof(FpsWorld).Assembly;
        using Stream stream = assembly.GetManifestResourceStream("AssettoServer.Server.Fps.fps.lua")
                              ?? throw new AssertionException("Embedded FPS client script was not found");
        using var reader = new StreamReader(stream);
        string script = reader.ReadToEnd();
        int topLevelLocalCount = script.Split('\n')
            .Count(line => line.StartsWith("local ", StringComparison.Ordinal));
        int snapshotStart = script.IndexOf("local snapshotEvent", StringComparison.Ordinal);
        int rosterStart = script.IndexOf("local rosterEvent", StringComparison.Ordinal);
        string snapshotDefinition = script[snapshotStart..rosterStart];
        int shotStart = script.IndexOf("local shotEvent", StringComparison.Ordinal);
        int meshStart = script.IndexOf("local function appendBox", StringComparison.Ordinal);
        string shotDefinition = script[shotStart..meshStart];
        int updateStart = script.IndexOf("function script.update(dt)", StringComparison.Ordinal);
        int frameBeginStart = script.IndexOf("function script.frameBegin", StringComparison.Ordinal);
        int draw3DStart = script.IndexOf("function script.draw3D", StringComparison.Ordinal);
        int directDrawStart = script.IndexOf("local function drawDirectRifleViewmodel",
            StringComparison.Ordinal);
        int localCollisionStart = script.IndexOf("local function localTrackProbeMovement",
            StringComparison.Ordinal);
        string updateDefinition = script[updateStart..frameBeginStart];
        string frameBeginDefinition = script[frameBeginStart..draw3DStart];
        int drawUiStart = script.IndexOf("function script.drawUI", StringComparison.Ordinal);
        string draw3DDefinition = script[draw3DStart..drawUiStart];
        string directDrawDefinition = script[directDrawStart..localCollisionStart];

        Assert.Multiple(() =>
        {
            Assert.That(topLevelLocalCount, Is.LessThanOrEqualTo(190),
                "CSP Lua rejects a main chunk with more than 200 locals; keep headroom for future additions.");
            Assert.That(script, Does.Not.Contain("ac.setCarActive"));
            Assert.That(script, Does.Contain("physics.setCarNoInput(true)"));
            Assert.That(script, Does.Contain("physics.setCarNoInput(false)"));
            Assert.That(script, Does.Contain("ac.findNodes('carRoot:' .. i)"));
            Assert.That(script, Does.Contain("root:setVisible(false)"));
            Assert.That(script, Does.Contain("ac.disableExtraHUDElements"));
            Assert.That(script, Does.Contain("'leaderboard'"));
            Assert.That(script, Does.Not.Contain("physics.lockUserControlsFor"));
            Assert.That(script, Does.Not.Contain("physics.lockUserGearboxFor"));
            Assert.That(script, Does.Contain("physics.setGentleStop(car.index, true)"));
            Assert.That(script, Does.Contain("physics.getCarInputControls()"));
            Assert.That(script, Does.Contain("ac.isKeyDown(positiveKey)"));
            Assert.That(script, Does.Contain("ac.KeyIndex.Up"));
            Assert.That(script, Does.Not.Contain("ui.keyboardButtonDown"));
            Assert.That(script, Does.Contain("}, function() end, nil, true)"));
            Assert.That(snapshotDefinition, Does.Contain("end, nil, true)"));
            Assert.That(shotDefinition, Does.Contain("end, nil, true"));
            Assert.That(script, Does.Contain("buttons = buttons }, false, 255)"));
            Assert.That(script, Does.Contain("not state.isInMainMenu"));
            Assert.That(script, Does.Contain("releaseFpsCamera()"));
            Assert.That(script, Does.Contain("camera, cameraError = ac.grabCamera"));
            Assert.That(script, Does.Contain("camera.ownShare = 1"));
            Assert.That(script, Does.Contain("fpsNearClip = 0.03"));
            Assert.That(script, Does.Contain("ac.overrideCameraClipPlanes(fpsNearClip, nil)"));
            Assert.That(script, Does.Contain("params.clipNear = fpsNearClip"));
            Assert.That(script, Does.Contain("restoreFpsClipPlane()"));
            Assert.That(script, Does.Contain("camera near-clip request:"));
            Assert.That(script, Does.Contain("nearClip=%.3f clipMethod=%s"));
            Assert.That(script, Does.Contain("camera:dispose()"));
            Assert.That(script, Does.Contain("function script.frameBegin"));
            Assert.That(updateDefinition, Does.Not.Contain("applyFpsCamera(localActor)"));
            Assert.That(frameBeginDefinition,
                Does.Contain("applyFpsCamera(localActor, viewmodelFrameDt)"));
            Assert.That(script, Does.Contain("local function probeFirstPersonCameraClearance"));
            Assert.That(script, Does.Contain("local function resolveFirstPersonCameraPosition"));
            Assert.That(script, Does.Contain("firstPersonCameraRadius = 0.24"));
            Assert.That(script, Does.Contain("for _ = 1, 4 do"));
            Assert.That(script, Does.Contain("camera.transform.position = resolveFirstPersonCameraPosition"));
            Assert.That(script, Does.Contain("first-person camera clearance engaged:"));
            Assert.That(script, Does.Contain("cameraCorrections=%d"));
            Assert.That(updateDefinition, Does.Not.Contain("updateRifleViewmodel(dt"));
            Assert.That(directDrawDefinition, Does.Contain(
                "updateRifleViewmodel(viewmodelFrameDt, actor, viewmodelMove, viewmodelSprint)"));
            Assert.That(draw3DDefinition, Does.Contain("drawDirectRifleViewmodel()"));
            Assert.That(script, Does.Contain("ac.KeyIndex.F6"));
            Assert.That(script, Does.Contain("third-person over-shoulder"));
            Assert.That(script, Does.Contain("physics.raycastTrack(focus, direction, distance"));
            Assert.That(script, Does.Contain("actor.root:setVisible(active and thirdPersonEnabled)"));
            Assert.That(script, Does.Contain(
                "render.setTransform(viewmodelRenderPosition, viewmodelRenderLook, viewmodelRenderUp, true)"));
            Assert.That(script, Does.Contain("ac.getCameraPosition():clone()"));
            Assert.That(script, Does.Contain("ac.getCameraForward():clone()"));
            Assert.That(script, Does.Contain("ac.getCameraUp():clone()"));
            Assert.That(script, Does.Contain("actor.root:setOrientation(vec3(math.sin(yaw)"));
            Assert.That(script, Does.Contain("groundYs = ac.StructItem.array"));
            Assert.That(script, Does.Contain("collisionDirections = ac.StructItem.array(ac.StructItem.byte()"));
            Assert.That(script, Does.Contain("collisionDirection / 254 * math.pi * 2"));
            Assert.That(script, Does.Contain("updateLocalThirdPersonAvatar(localActor)"));
            Assert.That(script, Does.Contain("local third-person avatar ready:"));
            Assert.That(script, Does.Contain("procedural-skinned-operator"));
            Assert.That(script, Does.Contain("local function drawRemoteActors()"));
            Assert.That(draw3DDefinition, Does.Contain("drawRemoteActors()"));
            Assert.That(script, Does.Contain("remoteRender.actorSnapshotCount = visibleActors"));
            Assert.That(script, Does.Contain("local function updateRemoteAvatar(actor)"));
            Assert.That(snapshotDefinition, Does.Contain("if id ~= localSessionID then"));
            Assert.That(snapshotDefinition, Does.Contain("actor.render:set(actor.target)"));
            Assert.That(script, Does.Contain("actor.root:setPosition(actor.target)"));
            Assert.That(script, Does.Contain("if actor.id ~= localSessionID then updateRemoteAvatar(actor) end"));
            Assert.That(script, Does.Contain("and not actor.remoteSceneReady then"));
            Assert.That(script, Does.Contain("persistent remote actor scene rendering ready:"));
            Assert.That(script, Does.Contain("render.setTransform(actor.target"));
            Assert.That(script, Does.Contain("return render.mesh(remoteAvatarRenderParams)"));
            Assert.That(script, Does.Contain("direct remote actor rendering ready:"));
            Assert.That(script, Does.Not.Contain("content/objects3D/pitcrew.kn5"));
            Assert.That(script, Does.Contain("'quickPitsMenu'"));
            Assert.That(script, Does.Contain("ac.disableQuickMenuPitstop(true)"));
            Assert.That(script, Does.Contain("ac.accessMouseDelta(true, true, true)"));
            Assert.That(script, Does.Contain("yaw = yaw - mouse.x"));
            Assert.That(script, Does.Contain("local keyboardX = -inputAxis"));
            Assert.That(script, Does.Contain("ac.isKeyDown(ac.KeyIndex.Space)"));
            Assert.That(script, Does.Contain("(jump and 4 or 0)"));
            Assert.That(script, Does.Contain("local avatarPosition = actor.render:clone()"));
            Assert.That(script, Does.Contain("local standingProbeHeights = {0.52, 0.9, 1.48}"));
            Assert.That(script, Does.Contain("predictedVerticalVelocity = 7.25"));
            Assert.That(script, Does.Contain("ac.KeyIndex.LeftControl"));
            Assert.That(script, Does.Contain("ac.KeyIndex.LeftMenu"));
            Assert.That(script, Does.Contain("ac.KeyIndex.C"));
            Assert.That(script, Does.Contain("(crouch and 8 or 0)"));
            Assert.That(script, Does.Contain("ac.KeyIndex.LeftButton"));
            Assert.That(script, Does.Contain("ui.mouseDown(ui.MouseButton.Left)"));
            Assert.That(script, Does.Contain("[ASRC FPS] fire input captured:"));
            Assert.That(script, Does.Contain("ac.KeyIndex.R"));
            Assert.That(script, Does.Contain("(reload and 16 or 0)"));
            Assert.That(script, Does.Contain("scoreboardHeld = ac.isKeyDown(ac.KeyIndex.Tab)"));
            Assert.That(script, Does.Contain("cursorUnlocked = scoreboardHeld or persistentCursor"));
            Assert.That(script, Does.Contain("if not cursorUnlocked then"));
            Assert.That(script, Does.Contain("ui.captureMouse(true)"));
            Assert.That(script, Does.Contain("ui.transparentWindow('asrc-fps-scoreboard-controls'"));
            Assert.That(script, Does.Contain("ui.checkbox('Keep mouse cursor visible after releasing TAB'"));
            Assert.That(script, Does.Contain("DEATHMATCH SCOREBOARD"));
            Assert.That(script, Does.Contain("bit.band(localActor.flags, 16)"));
            Assert.That(script, Does.Contain("bit.band(actor.flags, 64)"));
            Assert.That(script, Does.Contain("predictionCollisionConstrained = true"));
            Assert.That(script, Does.Contain("predictionClearSnapshots >= 3"));
            Assert.That(script, Does.Contain("[ASRC FPS] prediction collision constraint:"));
            Assert.That(script, Does.Contain("[ASRC FPS] prediction hard correction:"));
            Assert.That(updateDefinition, Does.Not.Contain("predictionCollisionLocked"));
            Assert.That(script, Does.Contain("bit.band(actor.flags, 128)"));
            Assert.That(script, Does.Contain("cameraHeight = math.lerp"));
            Assert.That(script, Does.Contain("physics.raycastTrack"));
            Assert.That(script, Does.Contain("localTrackProbeMovement"));
            Assert.That(script, Does.Contain("localTrackResolveMovement"));
            Assert.That(script, Does.Contain("collisionProbeOffsets = {-1, -0.5, 0, 0.5, 1}"));
            Assert.That(script, Does.Contain("if amount > 0 then"));
            Assert.That(script, Does.Contain("viewmodelWallRetraction"));
            Assert.That(script, Does.Contain("[ASRC FPS] first snapshot"));
            Assert.That(script, Does.Contain("[ASRC FPS] local actor snapshot acquired"));
            Assert.That(script, Does.Contain("[ASRC FPS] snapshot heartbeat"));
            Assert.That(script, Does.Contain("[ASRC FPS] input sample"));
            Assert.That(script, Does.Contain("[ASRC FPS] render state"));
            Assert.That(script, Does.Contain("[ASRC FPS] remote render state"));
            Assert.That(script, Does.Contain("[ASRC FPS] viewmodel render state"));
            Assert.That(script, Does.Contain("[ASRC FPS] viewmodel pipeline:"));
            Assert.That(script, Does.Contain("[ASRC FPS] viewmodel heartbeat:"));
            Assert.That(script, Does.Contain("[ASRC FPS] viewmodel stage:"));
            Assert.That(script, Does.Contain("callbacks=frameBegin:%d,draw3D:%d,drawUI:%d directDraw=%d/%d"));
            Assert.That(script, Does.Contain("ac.StructItem.key('ASRC_FpsClientDiagnostic')"));
            Assert.That(script, Does.Contain("remoteActorID = ac.StructItem.byte()"));
            Assert.That(script, Does.Contain("remoteTarget = ac.StructItem.vec3()"));
            Assert.That(script, Does.Contain("remoteRender = ac.StructItem.vec3()"));
            Assert.That(updateDefinition, Does.Not.Contain(
                "actor.render:set(math.lerp(actor.render, actor.target, blend))"));
            Assert.That(script, Does.Contain("pipeline = 12"));
            Assert.That(script, Does.Contain("viewmodel diagnostic sent to server:"));
            Assert.That(script, Does.Contain("[ASRC FPS] ready sent"));
            Assert.That(script, Does.Contain("ac.StructItem.key('ASRC_FpsShot')"));
            Assert.That(script, Does.Contain("createRifleModel = function"));
            Assert.That(script, Does.Contain("asrc_assault_rifle_viewmodel.kn5"));
            Assert.That(script, Does.Contain("asrc_assault_rifle_world.kn5"));
            Assert.That(script, Does.Contain("ac.getFolder(ac.FolderID.Root)"));
            Assert.That(script, Does.Contain("web.loadRemoteAssets"));
            Assert.That(script, Does.Contain("ac.getServerIP()"));
            Assert.That(script, Does.Contain("ac.getServerPortHTTP()"));
            Assert.That(script, Does.Contain("/fps/assets/asrc-fps-assets-v6.zip"));
            Assert.That(script, Does.Contain("asrc_rifle_diffuse.png"));
            Assert.That(script, Does.Contain("asrc_operator_skin.png"));
            Assert.That(script, Does.Contain("crucial = rifleViewmodelFileName"));
            Assert.That(script, Does.Contain("requesting rifle assets:"));
            Assert.That(script, Does.Contain("rifle assets cached:"));
            Assert.That(script, Does.Contain("forceRenderableOn = true"));
            Assert.That(script, Does.Contain("cached assault-rifle viewmodel loaded:"));
            Assert.That(script, Does.Contain("createNode('ASRC_FPS_VIEWMODEL_HOLDER', false)"));
            Assert.That(script, Does.Contain("model:setDepthMode(render.DepthMode.Off)"));
            Assert.That(script, Does.Contain("viewmodelRoot:getLocalAABB()"));
            Assert.That(script, Does.Not.Contain("viewmodelRoot:getChildrenCount()"));
            Assert.That(script, Does.Not.Contain("viewmodelHolder:setPosition(position)"));
            Assert.That(script, Does.Not.Contain("viewmodelHolder:setOrientation(look, up)"));
            Assert.That(script, Does.Not.Contain("viewmodelRoot:setPosition(position)"));
            Assert.That(script, Does.Contain("viewmodelRenderPosition = position:clone()"));
            Assert.That(script, Does.Contain("viewmodelRenderLook = look:clone()"));
            Assert.That(script, Does.Contain("viewmodelRenderUp = up:clone()"));
            Assert.That(script, Does.Not.Contain("render.setTransform(viewmodelRenderTransform, true)"));
            Assert.That(script, Does.Contain("return render.mesh(viewmodelRenderParams)"));
            Assert.That(script, Does.Contain("render.setDepthMode(render.DepthMode.Off)"));
            Assert.That(script, Does.Contain("direct assault-rifle viewmodel draw completed"));
            Assert.That(script, Does.Contain("cached rifle viewmodel failed:"));
            Assert.That(script, Does.Contain("FPS RIFLE ASSET DOWNLOAD FAILED - CHECK SERVER HTTP PORT"));
            Assert.That(script, Does.Not.Contain("clientAssetPath(rifleViewmodelRelativePath)"));
            Assert.That(script, Does.Contain("drawFallbackRifle(size)"));
            Assert.That(script, Does.Contain("function script.draw3D()"));
            Assert.That(script, Does.Contain("direct shot-effect templates ready"));
            Assert.That(script, Does.Contain("drawDirectShotEffects()"));
            Assert.That(shotDefinition, Does.Contain("from = muzzleOrigin:clone()"));
            Assert.That(shotDefinition, Does.Contain("flashFrom = muzzleOrigin:clone()"));
            Assert.That(shotDefinition, Does.Contain("to = targetPoint"));
            Assert.That(shotDefinition, Does.Contain("travelTime = math.clamp"));
            Assert.That(shotDefinition, Does.Contain("while #tracers >= maxTracers"));
            Assert.That(shotDefinition, Does.Contain("expiresAt = now + travelTime"));
            Assert.That(shotDefinition, Does.Contain("targetID = ac.StructItem.byte()"));
            Assert.That(shotDefinition, Does.Contain("targetSpawnCount"));
            Assert.That(shotDefinition, Does.Contain("first shot event received:"));
            Assert.That(shotDefinition, Does.Contain("while #impacts >= maxImpactMarks"));
            Assert.That(script, Does.Contain("maxImpactMarks = 96"));
            Assert.That(script, Does.Contain("(now - tracer.bornAt) / tracer.travelTime"));
            Assert.That(script, Does.Contain("if tracers[i].expiresAt <= visualNow"));
            Assert.That(script, Does.Contain("clearActorImpacts(message.victimID)"));
            Assert.That(script, Does.Contain("target.spawnCount ~= impact.targetSpawnCount"));
            Assert.That(script, Does.Contain("render.setTransform(tracer.flashFrom"));
            Assert.That(script, Does.Contain("render.mesh(tracerRenderParams)"));
            Assert.That(script, Does.Contain("render.mesh(impactRenderParams)"));
            Assert.That(script, Does.Contain("render.mesh(sparkRenderParams)"));
            Assert.That(script, Does.Not.Contain("render.debugLine(tracer.from, tracer.to"));
            Assert.That(script, Does.Not.Contain("render.debugPlane(impact.position"));
            Assert.That(script, Does.Contain("ac.Particles.Sparks"));
            Assert.That(script, Does.Contain("ac.Particles.Smoke"));
            Assert.That(snapshotDefinition, Does.Contain("ammo = ac.StructItem.array"));
            Assert.That(snapshotDefinition, Does.Contain("reserveMagazines = ac.StructItem.array"));
            Assert.That(snapshotDefinition, Does.Contain("reloadRemaining = ac.StructItem.array"));
            Assert.That(snapshotDefinition, Does.Contain("spawnCounts = ac.StructItem.array"));
            Assert.That(snapshotDefinition, Does.Contain("remote actor respawn reconciled:"));
            Assert.That(shotDefinition, Does.Contain("impact = ac.StructItem.byte()"));
            Assert.That(script, Does.Contain("textures = { txDiffuse = rifleDiffusePath }"));
            Assert.That(script, Does.Contain("textures = { txDiffuse = operatorSkinPath }"));
            Assert.That(script, Does.Contain("local operatorUV ="));
            Assert.That(script, Does.Contain("operatorUV.torso"));
            Assert.That(script, Does.Contain("operatorUV.pants"));
            Assert.That(script, Does.Contain("operatorUV.boot"));
            Assert.That(script, Does.Contain("procedural-skinned-operator"));
            Assert.That(script, Does.Contain("txDiffuse.SampleLevel(samLinear, pin.Tex, 0)"));
            Assert.That(script, Does.Contain("RELOADING  %.1fs"));
            Assert.That(script, Does.Contain("%02d  |  %d MAGS"));
            Assert.That(script, Does.Not.Contain("ASSAULT RIFLE  |  INFINITE"));
            Assert.That(script, Does.Contain("extension/audio/asrc_fps/rifle.wav"));
        });
    }
}
