<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>AssettoServer Race Control</AssemblyName>
    <ApplicationIcon>..\AssettoServer\Assets\assettoserver.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AssettoServer.RaceControl.Core\AssettoServer.RaceControl.Core.csproj" />
    <PackageReference Include="Vortice.D3DCompiler" Version="3.8.3" />
    <PackageReference Include="Vortice.Wpf" Version="3.8.3" />
  </ItemGroup>
  <Target Name="KeepSatelliteResourcesExternal"
          AfterTargets="ComputeResolvedFilesToPublishList"
          BeforeTargets="_ComputeFilesToBundle"
          Condition="'$(PublishSingleFile)' == 'true'">
    <ItemGroup>
      <ResolvedFileToPublish Update="@(ResolvedFileToPublish)"
                             Condition="'%(ResolvedFileToPublish.Extension)' == '.dll' and $([System.String]::Copy('%(ResolvedFileToPublish.Filename)').EndsWith('.resources'))">
        <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      </ResolvedFileToPublish>
    </ItemGroup>
  </Target>
</Project>
